# -*- coding: utf-8 -*-
"""web

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wimn3sIF05VQME8KY_gAVo_DHaMdb2vb
"""

import streamlit as st

st.subheader("Lung Cancer Mortality Rate Prediction project")
st.title("My goal,:smile:")
st.write("My name is Hannah Laichena and my goal was to create a model that would be able to predict the mortality rate of lung cancer patients and to also recommend better treatment methods to be used by the patients.")
st.write("I used a dataset from kaggle and the link is [https://www.kaggle.com/datasets/masterdatasan/lung-cancer-mortality-datasets-v2]. To view the EDA I performed on the dataset and the model I built checkout the git repository link [Lung_Cancer_EDA____Mortality_Prediction.ipynb]")